import { createPagesFunctionHandler } from "@react-router/cloudflare";

declare module "react-router" {
  export interface AppLoadContext {
    cloudflare: {
      env: Env;
      ctx: ExecutionContext;
    };
  }
}

// @ts-ignore - build generated by react-router build
const build = () => import("../build/server/index.js");

export const onRequest = createPagesFunctionHandler({ build });
