import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    route("checkout", "routes/checkout.tsx", [
        index("routes/checkout._index.tsx"),
        route("confirmation/:orderCode", "routes/checkout.confirmation.$orderCode.tsx"),
        route("success/:orderCode", "routes/checkout.success.tsx"),
    ]),
    index("routes/home.tsx"),
    route("products/:slug", "routes/product.tsx"),
    route("collections/:slug", "routes/collections.$slug.tsx"),
    route("cart", "routes/cart.tsx"),
    route("api/active-order", "routes/api/active-order.tsx"),
    route("api/wishlist", "routes/api/wishlist.tsx"),
    route("api/reviews", "routes/api/reviews.tsx"),
    route("api/rajaongkir", "routes/api/rajaongkir.tsx"),
    route("sign-in", "routes/sign-in.tsx"),
    route("sign-up", "routes/sign-up.tsx"),
    route("sign-up/success", "routes/sign-up.success.tsx"),
    route("forgot-password", "routes/forgot-password.tsx"),
    route("password-reset", "routes/reset-password.tsx"),
    route("verify", "routes/verify.tsx"),
    route("api/logout", "routes/api/logout.ts"),
    route("api/cache-purge", "routes/api/cache-purge.ts"),
    route(".well-known/appspecific/com.chrome.devtools.json", "routes/chrome-devtools.ts"),
    route("about", "routes/about.tsx"),
    route("contact", "routes/contact.tsx"),
    route("faq", "routes/faq.tsx"),
    route("returns", "routes/returns.tsx"),
    route("shipping", "routes/shipping.tsx"),
    route("blog", "routes/blog._index.tsx"),
    route("blog/:slug", "routes/blog.$slug.tsx"),
    route("community", "routes/community.tsx"),
    route("highlights", "routes/highlights.tsx"),
    route("size-guide", "routes/size-guide.tsx"),
    route("terms", "routes/terms.tsx"),
    route("privacy", "routes/privacy.tsx"),
    route("account", "routes/account.tsx", [
        index("routes/account._index.tsx"),
        route("history", "routes/account.history.tsx"),
        route("wishlist", "routes/account.wishlist.tsx"),
        route("password", "routes/account.password.tsx"),
        route("addresses", "routes/account.addresses.tsx", [
            route("new", "routes/account.addresses.new.tsx"),
            route(":addressId", "routes/account.addresses.$addressId.tsx"),
        ]),
    ]),
] satisfies RouteConfig;
